// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://metmlywokvyrufgznnhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ldG1seXdva3Z5cnVmZ3pubmhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0ODU5NjcsImV4cCI6MjA1NjA2MTk2N30.Ukafx22nUiDWSYS61MiwmB66hWTuoqKf-WM3MPeepzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);